name: linting, testing, building
on:
  push:
    branches: [bnbnbnbnbn]
  pull_request:
    branches: [bnbnbnbnbn]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production
        run: npm run build:prod
        if: always()
      - name: lint ts
        run: npm run lint:ts
        if: always()
      - name: lint css
        run: npm run lint:scss
      - name: test unit
        run: npm run test:unit
        if: always()
      - name: build storybook
        run: npm run storybook:build
        if: always()
      # - name: screenshot test
      #   run: npm run test:ui
      #   if: always()
