name: Build project
on: 
  push:
    branches: [ bnbnbnbnbn ] 
  pull_request:
    branches: [ bnbnbnbnbn ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]


    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-verson: ${{ matrix.node-version }}
      - name: install modules
        run: yarn add

      - name: build production
        run: yarn build:prod

      - name: lint ts
        run: yarn lint:ts

      - name: lint scss
        run: yarn lint:scss

      - name: jest testing
        run: yarn test:unit

      - name: loki testing
        run: yarn test:ui

      - name: jest testing
        run: yarn test:unit

      - name: jest testing
        run: yarn test:unit

