name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install yarn ts-node for preinstall
        run: yarn add ts-node
      - name: install modules
        run: yarn install --force
      - name: build production
        run: yarn build:prod
        if: always()
      - name: lint ts
        run: yarn lint:ts
        if: always()
      - name: lint css
        run: yarn lint:scss
      - name: test unit
        run: yarn test:unit
        if: always()
      - name: build storybook
        run: yarn storybook:build
        if: always()
      - name: screenshot test
        run: yarn test:ui
        if: always()
