name: Build project
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: [ bnbnbnbnbn ] 
  pull_request:
    branches: [ bnbnbnbnbn ]
jobs:
  pipeline:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [ 17.x ]


  steps:
    - uses: action/checkout@v2
    - name: Starting Node.js ${{ matrix, node-version }}
      uses: action/setup-node@v1
      with:
        node-verson: ${{ matrix.node-version }}
    - name: install modules
      run: yarn install --dev

    - name: build production
      run: yarn build:prod

    - name: lint ts
      run: yarn lint:ts

    - name: lint scss
      run: yarn lint:scss

    - name: jest testing
      run: yarn test:unit

    - name: loki testing
      run: yarn test:ui

    - name: jest testing
      run: yarn test:unit

    - name: jest testing
      run: yarn test:unit

