name: Build project
on: 
  push:
    branches: [ bnbnbnbnbn ] 
  pull_request:
    branches: [ bnbnbnbnbn ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-node-version: [ 18.x ]


    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-node-version }}
        uses: actions/setup-node@v1
        with:
          node-node-version: ${{ matrix.node-node-version }}
      - name: install modules
        run: npm i -D 

      - name: build production
        run: npm run build:prod

      - name: lint ts
        run: npm run lint:ts

      - name: lint scss
        run: npm run lint:scss

      - name: jest testing
        run: npm run test:unit

      - name: loki testing
        run: npm run test:ui

      - name: jest testing
        run: npm run test:unit

      - name: jest testing
        run: npm run test:unit

